### ISSUE TITLE
Browserfied softap has problems on iOS 10 browsers

### ISSUE THREAD

**Issue by steelydev** [spark/softap-setup-js#22]
We are using Photons running 0.5.1

We have been using a softap since Particle firmware 0.4.7 and it has been working fine on all platform/browser combinations.  

Until iOS 10.  

Now it hangs when retrieving any info from the Photon.

I tried to follow execution with iPad hooked to iMac, but I'm not sure what to look for.

We depend on softap-setup to configure our product to customer's WiFi.  Any ideas would be appreciated.

**Comment by anigo333** [comment]
we are in the same boat, any leads yet?

**Comment by steelydev** [comment]
Because I read that this project has "not been taken over the finish line", I decided to abandon it, myself.

I have rewritten most of softap's functionality in javascript and jQuery:

[softap.zip](https://github.com/spark/softap-setup-js/files/561535/softap.zip)

This steals heavily from an example of loading html pages directly onto the Photon.  I decided against that approach because we need to configure WiFi from our web site.

**Comment by brycekahle** [comment]
Can you elaborate on your setup? Are you using the HTTP version of SoftAP? You are loading this in Safari on iOS 10?

If you connect your device to a Mac and use the Safari DevTools, you can connect to the device and see the error console. See https://blog.idrsolutions.com/2015/02/remote-debugging-ios-safari-on-os-x-windows-and-linux/

**Comment by anigo333** [comment]
We have a PhoneGap App which runs on both IOS and Android, the app makes use of the SoftAP JS to connect to the Particle powered device. From my last check PhoneGap doesn't have a great support for TCP so we went with the HTTP version of SoftAP.

On IOS 10 after connecting the debugger, from both the app and Safari i see errors thrown either when it is trying to scan the wifi networks or when it is attempting to connect to it.

However, I would like to ask one thing.. it seems[ the actual issue is fixed with 0.51 firmware](https://github.com/spark/firmware/issues/937), why is it still logged as a warning on the softap page?

**Comment by brycekahle** [comment]
What were the errors? Can you paste them here? I know PhoneGap does some odd things with `Origin`, so you might be running into CORS issues.

RE: warning => Not everyone is running `0.5.1`. I can change the message to mention that it was fixed in `0.5.1`.

**Comment by anigo333** [comment]
will share details later tonight. I should mention that phonegap has been working all this while with IOS9,  we did not change anything on our side but it stopped working with IOS 10. 

Are you saying that phonegap changes certain properties under the hood specific to IOS 10?

**Comment by brycekahle** [comment]
I think it is much more likely that iOS 10 Safari made some changes that make it now incompatible. The errors will help us figure that out.

**Comment by anigo333** [comment]
sorry, I still can't get you a clean repro. I am using an older and minified version of this library and it seems to be failing inside the node-rsa module while attempting to read the publickey.

Attempting to run using the latest version of this repo, I am running into undocumented issues in just a few obtaining the deviceInfo. 

Are you sure that I have to use the softap-setup-js and not httpsoftap.js to build the browserified version? Using softap-setup-js version throws a not implemented exception even though I initialized it with http protocol.

**Comment by anigo333** [comment]
Alright, the issue is with RSA library that SoftAP.js uses. I confirm that it works in Windows Chrome, but breaks on Mac Safari and IOS as well.. To repro head to http://gethook.io/repro, if it works in your browser it will print the public key else will print the callstack.

the source is available here
https://github.com/krazineurons/softap-js-repro/

**Comment by brycekahle** [comment]
@krazineurons Thanks for digging in and finding the root problem. Do you know which version starts causing errors? You could (or we can if you like) file a bug upstream to get this fixed in `node-rsa` once you have that information.

Once we know the version, we can also pin the version `softap-setup-js` uses to unblock everyone.

**Comment by anigo333** [comment]
by version you mean ios version? My guess is the first public release of ios 10 would do it, have had only the ios 10 customers reported it. I am not sure how much of DNA does safari on Mac and ios share, because it is happening on both of them.

possible to engage with node-rsa folks to look into the inner workings and have them work out the version that works break it?

**Comment by anigo333** [comment]
Hi, not sure where do I go from here. Any inputs on how to fix it?
Shouldn't particle be driving this as it impacts all HTTP based particle
apps?

**Comment by steelydev** [comment]
Have you check out the .zip file I posted a while ago?

**Comment by TechMaz** [comment]
Hi everyone. Any updates over the last week? The softap module is extremely important to our application and we have been unable to connect our Photon devices on iOS10 devices and safari on mac for several weeks.

**Comment by steelydev** [comment]
Did you take a look at the .zip file I posted?

-Geoff

====================
35 Hawthorne Pt
Little Deer Isle, ME 04650
(207) 702-1713 (mobile)
(207) 348-6404 (not mobile)

**Comment by towynlin** [comment]
Thanks for the continued reports and comments folks; sorry about the radio silence. I'll ping someone on the team to follow up again. We're focused on wrapping up sprint goals for the end of the year. Progress on this will most likely be in January.

**Comment by m-mcgowan** [comment]
Thanks for the repro test - very useful! I ran this on OSX El Capitan/Safari and managed to reproduce the issue, which was not repro'd on Chrome. 

After rerunning browserify, it then started working on Safari also, so it could be a browserify bug or a node-rsa bug that has been fixed in the meantime. Just mentioning this in case someone has bandwidth to pursue that line of investigation before we can turn to this in January.

**Comment by m-mcgowan** [comment]
@steelydev did you intend to close this? Unless the issue has been resolved,  it's best to keep it open so it's on our radar. Of course, if you have other thoughts please let us know :-)

**Comment by steelydev** [comment]
Yes. 

-Geoff

====================
35 Hawthorne Pt
Little Deer Isle, ME 04650
(207) 702-1713 (mobile)
(207) 348-6404 (not mobile)

**Comment by m-mcgowan** [comment]
Ok. Care to elaborate? Has the issue been resolved, and if so, what was the resolution?

**Comment by steelydev** [comment]
Maybe I’m using close wrong.  

I have solved the issue and posted a solution.  I realize Browserfied softap is broken as stated and has not been corrected.  So keep it open?

-Geoff

====================
35 Hawthorne Pt
Little Deer Isle, ME 04650
(207) 702-1713 (mobile)
(207) 348-6404 (not mobile)

**Comment by TechMaz** [comment]
Even if you have found a way of getting around it, probably should keep it open until the issue is resolved in the master branch of this repo.

**Comment by TechMaz** [comment]
@m-mcgowan re-running browserify isn't working for me. It looks like softap-setup relies on the dependency node-rsa@0.2.32, while the newest version of node-rsa is 0.4.2. I wonder if that has something to do with it? 

When testing in our app on safari browser, no error is produced if we try to connect to a device using softap-setup while the computer is not connected to the Photon-XXXX network. So up to that point things are fine. The error seems to occur at some point after the device has been successfully discovered and returns the device id to our server. After that, the following error appears in the console: 

<img width="534" alt="screen shot 2016-12-16 at 7 19 45 pm" src="https://cloud.githubusercontent.com/assets/2186709/21284057/c5f91d4e-c3c4-11e6-85c4-9b10d4533148.png">

Anyone who understands this stuff better know of any way to get around this error?
 Thanks.

P.S.  @steelydev  I appreciate you creating a version that works for you in jquery and javascript, but I am hoping to get this working using the actual softap-setup package for node if possible.

**Comment by m-mcgowan** [comment]
@TechMaz  - did you try the repo made by @krazineurons  here - https://github.com/spark/softap-setup-js/issues/22#issuecomment-258654089 - that's what I was referring to when I said re-running browserify helped. This might confirm that simply updating the node-rsa version is all that's needed. You might also try updating the node-rsa version in the softap-setup package to see if that helps resolve things. I'm sorry I cannot look into this more at present but it will get our full attention in early Q1 next year.

**Comment by steelydev** [comment]
@TechMaz I concur with your error message.  @m-mcgowan I think the problem is with the RSA stuff.

**Comment by anigo333** [comment]
i recompiled the repro.js file using latest version of node-rsa (0.4.2) but received the same error. the repro is on http://gethook.io/repro1

so at this point only option is to use the zip file by @steelydev instead of using the official particle solution.

**Comment by anigo333** [comment]
the issue is indeed with node-rsa, i used @steelydev's code changes and patched the node-rsa usage with RSAKey class and it is all working fine! Thanks a lot @steelydev

**Comment by steelydev** [comment]
@krazineurons not a problem.  I take no credit for the RSA library.  It is from here: https://docs.particle.io/reference/firmware/photon/#complete-example

**Comment by m-mcgowan** [comment]
I plan to look into this during the coming week.

**Comment by m-mcgowan** [comment]
I reproduced the earlier results - rerunning browserify against the latest node-rsa fixes the repo example above in Safari.  

So I did a more complete example using SoftAP to configure a photon to connect to a WiFi network (which uses the node-rsa functionality.) This worked on Safari for me. I hope others can verify too. 

The test case is here - https://github.com/spark/softap-setup-js/pull/28

**Comment by TechMaz** [comment]
@m-mcgowan What do you mean by the latest node-rsa fixes? The package hasn't been updated in a while.

**Comment by m-mcgowan** [comment]
The last release of softap-setup-js used node-rsa version 0.2.23, which was released on 2015-03-12.  The latest version of node-rsa is 0.4.2, released on 2016-09-19, so plenty of changes to catch up on there. 

From my testing in Safari, upgrading to node-rsa 0.4.2 fixes the problem that we see with the rsa library not working.

**Comment by TechMaz** [comment]
@m-mcgowan  Yes but I tried switching out the node-rsa package being used by softap-setup in my node_modules with the new one (0.4.2). Sadly after building, the same error occurred on Safari browsers. Perhaps if you were able to create a working edited version of the most recent softap-setup release package using node-rsa@0.4.2, I would appreciate it if you uploaded it here in order for me to test it myself? Perhaps I didn't copy something over correctly.

**Comment by m-mcgowan** [comment]
please try the test case here - https://github.com/spark/softap-setup-js/issues/22#issuecomment-277913599 and the PR

**Comment by incorvia** [comment]
@TechMaz Were you able to fix the Expected 0x2 error? We are using React Native and not using a browser but running into the same issue. Unsure of what is going wrong.

I should add I've tried downloading the pull request and doesn't seem to make a difference.

**Comment by incorvia** [comment]
@m-mcgowan I'm confused about the problem that this particular Github issue relates to. The error I am receiving is:

    Expected 0x2: got 0x30

with a call stack of:

    newInvalidAsn1Error
    readString
    publicImport
    detectAndImport
    importKey
    NodeRSA
    response
    socketCLose

This appears to be the same issue that @TechMaz is referencing despite that I am doing this within ReactNative (iOS10). Is this the same error that people are referring to here and that which a fix has been tested for?

**Comment by incorvia** [comment]
I seem to have fixed the issue of my dreaded bug:

    Expected 0x2: got 0x30

I did this through upgrading to the latest node-rsa 0.4.2 package + upgrading to the latest Buffer version of 5.0.5. It appears that in my instance the act of rn-nodefying react-native-crypto via:

    rn-nodeify -install crypto --hack

Installed buffer version 3.0.3. Upgrading to the latest Buffer version seems to have fixed my issue. Little difference use case then what other people say here but it appears that by regenerating Browserify it brings in the right node-rsa & buffer dependencies.

**Comment by m-mcgowan** [comment]
> regenerating Browserify it brings in the right node-rsa & buffer dependencies.
Yes, that's what I am seeing too, and the packages were updated to pull in the latest versions. 

There's been little activity here, so I'm going to say this is fixed.  Happy to re-open if details to the contrary come to light.
